### ISSUE TITLE
Improve quicklisp setup & documentation

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/oatmeal#22]
Currently you have to have quicklisp set up for `make` of an Oatmeal'ed app to work correctly.

This could be made less surprising with a script users can run, documented in the README and installed as part of the `brew` install.

**Comment by eigenhombre** [comment]
@coreagile I think this is done.  Would you be willing to review the README changes and/or comment on the approach?

**Comment by coreagile** [comment]
Looks fantastic! Thanks!!

Stephen Castro-Starkey
empathy | connectedness | restorative | relator | belief

secure email: https://keybase.io/scstarkey <https://keybase.io/scstarkey> 

Gallup Certified Strengths Coach
